const KNOWLEDGE = [
  {id:"company",category:"company",title:"MIG FARM company information",keywords:["mig farm","ميج فارم","الشركة","company","agriculture","زراعة"],content:"MIG FARM / MIG FOR AGRICULTURE is a UAE agricultural supplies business. Main categories include seeds, fertilizers and plant nutrition, irrigation and hydroponics, tools and equipment, and agricultural services."},
  {id:"contacts",category:"contact",title:"MIG FARM contact details",keywords:["واتساب","whatsapp","هاتف","phone","اتصال","contact","ايميل","email","فرع","branch"],content:"Al Ain phone and WhatsApp: +971 58 176 8215. Sharjah phone: +971 54 702 5904. Email: sales@migfarm.com. Website: https://www.migfarm.com. Branches: Al Ain and Sharjah, United Arab Emirates."},
  {id:"shipping",category:"shipping",title:"Standard UAE delivery",keywords:["شحن","shipping","delivery","توصيل","13","درهم","aed"],content:"The currently configured standard delivery charge is AED 13 for UAE delivery. Do not claim anything about VAT inclusion unless that information is added later."},
  {id:"pepper",category:"seeds",title:"Pepper seed varieties",keywords:["فلفل","pepper","جمر","jamra","شهاب","shihab","شرارة","sharara","الكوس","kous","جميرا","jumeirah","البرشا","barsha"],content:"Known MIG FARM pepper seed varieties include hot pepper: جمر (Jamra), شهاب (Shihab), شرارة (Sharara), الكوس (Al Kous); and sweet pepper: جميرا الأصفر (Jumeirah Yellow), البرشا الأخضر (Al Barsha Green). Do not invent agronomic specifications, resistance claims, prices, or current stock unless supplied in product context or later knowledge."},
  {id:"eggplant",category:"seeds",title:"Eggplant seed varieties",keywords:["باذنجان","eggplant","عتيق","ateeq","مياسة","mayasa","مزيونة","mazouna"],content:"Known MIG FARM eggplant varieties include عتيق F1 (Ateeq F1), مياسة F1 (Mayasa F1), and مزيونة الأبيض F1 (Mazouna White F1). Do not invent missing agronomic specifications, prices, or current stock."},
  {id:"cucumber",category:"seeds",title:"Cucumber seed varieties",keywords:["خيار","cucumber","jabaara","جبارة","wafra","وفرة"],content:"Known MIG FARM cucumber seed varieties include JABAARA and WAFRA F1. Use current product page context when available for exact price, SKU, availability, and packaging. Do not invent missing specifications."},
  {id:"sales-guidance",category:"sales",title:"Sales conversation guidance",keywords:["اختار","اختيار","انسب","مناسب","recommend","choose","best","اشتري","شراء"],content:"When recommending agricultural products, ask only the context that is actually needed. Useful details can include crop or product type, open field versus greenhouse, emirate, required quantity, planting timing, and desired result. Do not ask every question if the answer can already be inferred from the conversation or current product page."}
];
function normalize(value=""){return String(value).toLowerCase().normalize("NFKD").replace(/[\u064B-\u065F\u0670]/g,"").replace(/[أإآ]/g,"ا").replace(/ى/g,"ي").replace(/[^\p{L}\p{N}]+/gu," ").trim();}
export function retrieveKnowledge(query,productContext=null,limit=6){const normalized=normalize(`${query} ${productContext?JSON.stringify(productContext):""}`);const terms=normalized.split(/\s+/).filter(t=>t.length>1);return KNOWLEDGE.map(entry=>{const haystack=normalize([entry.title,entry.category,entry.content,...(entry.keywords||[])].join(" "));let score=0;for(const term of terms){if(haystack.includes(term))score+=2;if((entry.keywords||[]).some(k=>normalize(k)===term))score+=3;}return {entry,score};}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,limit).map(x=>x.entry);}
export function formatKnowledge(entries){if(!entries.length)return "No directly matching internal knowledge was found.";return entries.map((e,i)=>`[${i+1}] ${e.title}\n${e.content}`).join("\n\n");}
